# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Hook": "fastai-hooks.ipynb",
         "hook_output": "fastai-hooks.ipynb",
         "Hooks": "fastai-hooks.ipynb",
         "hook_outputs": "fastai-hooks.ipynb",
         "maybe_gather": "fastai-hooks.ipynb",
         "to_detach": "fastai-hooks.ipynb",
         "apply": "fastai-hooks.ipynb",
         "ConvLayer": "unet.ipynb",
         "SpatialAttention": "unet.ipynb",
         "UnetBlock3D": "unet.ipynb",
         "DeepSupervision": "unet.ipynb",
         "SqueezeExcitation": "unet.ipynb",
         "DynamicUnet3D": "unet.ipynb",
         "create_body": "utils.ipynb",
         "in_channels": "utils.ipynb",
         "first": "utils.ipynb",
         "dummy_eval": "utils.ipynb",
         "model_sizes": "utils.ipynb"}

modules = ["fastai_hooks.py",
           "unet.py",
           "utils.py"]

doc_url = "https://kbressem.github.io/attention_unet/"

git_url = "https://github.com/kbressem/attention_unet/tree/main/"

def custom_doc_links(name): return None
