# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"ConvLayer": "blocks.ipynb",
         "DropConnect": "blocks.ipynb",
         "SqueezeExpand": "blocks.ipynb",
         "MBConvBlock": "blocks.ipynb",
         "SpatialAttention": "blocks.ipynb",
         "UnetBlock": "blocks.ipynb",
         "BasicResBlock": "blocks.ipynb",
         "UNet": "modular_unet.ipynb",
         "ModularUNet": "modular_unet.ipynb",
         "UResNet18": "modular_unet.ipynb",
         "all_equal": "utils.ipynb",
         "first_layer": "utils.ipynb",
         "hasattrs": "utils.ipynb"}

modules = ["blocks.py",
           "modular_unet.py",
           "utils.py"]

doc_url = "https://kbressem.github.io/attention_unet/"

git_url = "https://github.com/kbressem/attention_unet/tree/main/"

def custom_doc_links(name): return None
