# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"create_body": "00_utils.ipynb",
         "in_channels": "00_utils.ipynb",
         "first": "00_utils.ipynb",
         "dummy_eval": "00_utils.ipynb",
         "model_sizes": "00_utils.ipynb",
         "Hook": "00_utils.ipynb",
         "hook_output": "00_utils.ipynb",
         "Hooks": "00_utils.ipynb",
         "hook_outputs": "00_utils.ipynb",
         "maybe_gather": "00_utils.ipynb",
         "to_detach": "00_utils.ipynb",
         "apply": "00_utils.ipynb",
         "ConvLayer": "01_unet.ipynb",
         "SpatialAttention": "01_unet.ipynb",
         "UnetBlock3D": "01_unet.ipynb",
         "DeepSupervision": "01_unet.ipynb",
         "SqueezeExcitation": "01_unet.ipynb",
         "DynamicUnet3D": "01_unet.ipynb"}

modules = ["utils.py",
           "unet.py"]

doc_url = "https://kbressem.github.io/attention_unet/"

git_url = "https://github.com/kbressem/attention_unet/tree/main/"

def custom_doc_links(name): return None
