# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/utils.ipynb (unless otherwise specified).

__all__ = ['all_equal']

# Cell
# default_exp utils

# Cell
def all_equal(iterator):
    " Check if all elements of a list are equal (https://stackoverflow.com/a/3844832/12995344)"
    iterator = iter(iterator)
    try:
        first = next(iterator)
    except StopIteration:
        return True
    return all(first == x for x in iterator)